### ISSUE TITLE
[0.1.2] INTERNALERROR with h5py

### ISSUE THREAD

**Issue by olebole** [astropy/pytest-astropy-header#38]
During the packaging of astropy 5.0RC1, I observed the following problem, which seems to be related to pytest-astropy-header: When trying to test astropy with h5py, this internal error appears:
```
============================= test session starts ==============================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3/dist-packages/_pytest/main.py", line 267, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
[…]
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3/dist-packages/pytest_astropy_header/display.py", line 150, in pytest_report_header
INTERNALERROR>     module = resolve_name(module_name)
INTERNALERROR>   File "/build/astropy-5.0~rc1/.pybuild/cpython3_3.9/build/astropy/tests/helper.py", line 312, in __exit__
INTERNALERROR>     treat_deprecations_as_exceptions()
INTERNALERROR>   File "/build/astropy-5.0~rc1/.pybuild/cpython3_3.9/build/astropy/tests/helper.py", line 224, in treat_deprecations_as_exceptions
INTERNALERROR>     del module.__warningregistry__
INTERNALERROR> TypeError: can't set attributes of built-in/extension type 'h5py._debian_h5py_serial.h5r.Reference'
E: pybuild pybuild:354: test: plugin distutils failed with: exit code=3: cd '/build/astropy-5.0~rc1/.
```

I am not sure whether this is bug in the h5py package; however I could imagine that limiting the catch to ImportErrors is too tight here: https://github.com/astropy/pytest-astropy-header/blob/210f926ffe5b093f11aebc03dae3d253a191a280/pytest_astropy_header/display.py#L148-L152

In the current "main" branch, the `resolve_name` is replaced by `importlib.import_module`, but this should make no difference.

**Comment by astrofrog** [comment]
This is a duplicate of https://github.com/astropy/astropy/issues/12388 I think, which has a related PR with a fix. Do you agree we can close this?

**Comment by olebole** [comment]
Ahh yes, I didn't see that.
